.TH NCMINES 6
.SH NAME
ncmines \- Terminal-based minesweeper clone
.SH SYNOPSYS
.B ncmines
<\fIeasy\fR|\fImedium\fR|\fIhard\fR>
.SH DESCRIPTION
Play minesweeper in the terminal moving the cursor with either the vim
movement keys or the arrow keys, setting flags with the 'f' key, and
uncovering tiles with the space or enter keys. Press 'q' at any time to
quit.

The terminal \fBMUST\fR be large enough to accomodate the playing field
and header.
.SH DIFFICULTIES
Easy \- 10x10, 15 mines

Medium \- 16x16, 40 mines

Hard \- 30x16, 99 mines
